version: 2

sources:
  - name: northwind
    description: Data from northwind ERP
    database: northwind  
    schema: raw_northwind  
    tables:
      - name: _ORDER_
        freshness:
          warn_after:
            count: 5000
            period: day
          error_after:
            count: 10000
            period: day
        loaded_at_field: cast(orderdate as timestamp)
        description: '{{ doc("orders_docs") }}'
        columns:
          - name: id
            description: Unique ID for this table
            tests:
              - unique
              - not_null
          - name: customerid
            tests:
              - relationships:
                  to: source('northwind', 'customers')
                  field: id

      - name: CUSTOMER
        description: This table lists the customers from ERP Northwind
        columns:
          - name: id
            description: Unique ID for this table
      - name: ORDERDETAIL
      - name: PRODUCT
        description: This table lists the products from ERP Northwind
        columns:
          - name: id
            description: Unique ID for this table
      - name: SUPPLIER
        description: This table lists the customers from ERP Northwind
        columns:
          - name: id
            description: Unique ID for this table